Add git fallback to template

diff --git a/go-template b/go-template
--- a/go-template
+++ b/go-template
@@ -49,23 +49,53 @@ declare GO_SCRIPT_BASH_REPO_URL="${GO_SCRIPT_BASH_REPO_URL:-https://github.com/m
 # URL with the release files
 declare GO_SCRIPT_BASH_DOWNLOAD_URL="${GO_SCRIPT_BASH_DOWNLOAD_URL:-${GO_SCRIPT_BASH_REPO_URL%.git}/archive}/$GO_SCRIPT_BASH_VERSION.tar.gz"
 
-
 if [[ ! -e "$GO_SCRIPT_BASH_CORE_DIR/go-core.bash" ]]; then
-  printf "Downloading framework from '%s'...\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL"
-  curl -LfsS "$GO_SCRIPT_BASH_DOWNLOAD_URL" | tar -xz
-  if [[ ${PIPESTATUS[0]} -ne 0 ]] || [[ ${PIPESTATUS[1]:1} -ne 0 ]] ; then
-    printf "Failed to download from '%s'; aborting.\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL" >&2
-    exit 1
+  declare PIPEFAIL_BACKUP
+  PIPEFAIL_BACKUP=$(shopt -op | grep pipefail)
+  set -o pipefail
+  
+  # Using a function to allow for multiple return points
+  curl_download(){
+    if ! command curl -V >/dev/null; then
+      printf "Failed to find cURL or tar\n"
+      return 1
+    fi
+    if ! command tar -h >/dev/null; then
+      printf "Failed to find cURL or tar\n"
+      return 1
+    fi
+    printf "Downloading framework from '%s'...\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL"
+    if ! curl -LfsS "$GO_SCRIPT_BASH_DOWNLOAD_URL" | tar -xz ; then
+      printf "Failed to download from '%s'.\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL" >&2
+      return 1
+    fi
+    if ! mkdir -p $GO_SCRIPTS_DIR ; then
+      printf "Failed to create scripts dir '%s'" $GO_SCRIPTS_DIR >&2
+      rm -rf go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER
+      return 1
+    fi
+    if ! mv go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER $GO_SCRIPT_BASH_CORE_DIR; then
+      printf "Failed to install downloaded directory in '%s'\n" $GO_SCRIPT_BASH_CORE_DIR >&2
+      rm -rf go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER
+      return 1
+    fi
+    printf "Download of '%s' successful.\n\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL"
+    return 0
+  }
+  
+  if ! curl_download; then
+    printf "Using git clone as fallback\n"
+    printf "Cloning framework from '%s'...\n" "$GO_SCRIPT_BASH_REPO_URL"
+    if ! git clone --depth 1 -c advice.detachedHead=false \
+        -b "$GO_SCRIPT_BASH_VERSION" "$GO_SCRIPT_BASH_REPO_URL" \
+        "$GO_SCRIPT_BASH_CORE_DIR"; then
+      printf "Failed to clone '%s'; aborting.\n" "$GO_SCRIPT_BASH_REPO_URL" >&2
+      $PIPEFAIL_BACKUP
+      exit 1
+    fi
+    printf "Clone of '%s' successful.\n\n" "$GO_SCRIPT_BASH_REPO_URL"
   fi
-  if ! mkdir -p $GO_SCRIPTS_DIR; then
-    printf "Faild to create scripts dir '%s'" $GO_SCRIPTS_DIR >&2
-    exit 2
-  fi
-  if ! mv go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER $GO_SCRIPT_BASH_CORE_DIR; then
-    printf "Failed to install downloaded directory in '%s'\n" $GO_SCRIPT_BASH_CORE_DIR >&2
-    exit 3
-  fi
-  printf "Download of '%s' successful.\n\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL"
+  $PIPEFAIL_BACKUP
 fi
 
 . "$GO_SCRIPT_BASH_CORE_DIR/go-core.bash" "$GO_SCRIPTS_DIR"
