go-template: Test in TEST_GO_ROOTDIR, fix quoting
Don't know why the test wasn't originally written using
`TEST_GO_ROOTDIR`. As intended, it exposed some missing quotes from
variables in `go-template` introduced in #179.

I've removed several instances of the following comment, as I'm not sure
it applies anymore. If it does, I'll make sure to restore it as needed:

  # Use `.*/scripts/go-script-bash` to account for the fact that `git clone` on
  # MSYS2 will output `C:/Users/<user>/AppData/Local/Temp/` in place of `/tmp`.

diff --git a/go-template b/go-template
--- a/go-template
+++ b/go-template
@@ -68,14 +68,15 @@ if [[ ! -e "$GO_SCRIPT_BASH_CORE_DIR/go-core.bash" ]]; then
       printf "Failed to download from '%s'.\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL" >&2
       return 1
     fi
-    if ! mkdir -p $GO_SCRIPTS_DIR ; then
-      printf "Failed to create scripts dir '%s'\n" $GO_SCRIPTS_DIR >&2
-      rm -rf go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER
+    if ! mkdir -p "$GO_SCRIPTS_DIR" ; then
+      printf "Failed to create scripts dir '%s'\n" "$GO_SCRIPTS_DIR" >&2
+      rm -rf "go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER"
       return 1
     fi
-    if ! mv go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER $GO_SCRIPT_BASH_CORE_DIR; then
-      printf "Failed to install downloaded directory in '%s'\n" $GO_SCRIPT_BASH_CORE_DIR >&2
-      rm -rf go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER
+    if ! mv "go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER" "$GO_SCRIPT_BASH_CORE_DIR"; then
+      printf "Failed to install downloaded directory in '%s'\n" \
+        "$GO_SCRIPT_BASH_CORE_DIR" >&2
+      rm -rf "go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER"
       return 1
     fi
     printf "Download of '%s' successful.\n\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL"
