template: Don't send git clone output to /dev/null
Previously I'd squelched the output because of the verbosity of the
`detached HEAD` warning when making a shallow clone, but it's not really
necessary anymore given `-c advice.detachedHead=false`. Now that the
`template` test is failing on Travis, I really need to see the output:

https://travis-ci.org/mbland/go-script-bash/jobs/200472791
https://travis-ci.org/mbland/go-script-bash/jobs/200472885

diff --git a/go-template b/go-template
--- a/go-template
+++ b/go-template
@@ -40,14 +40,14 @@ readonly GO_SCRIPT_BASH_CORE="$SCRIPTS_DIR/go-script-bash/go-core.bash"
 readonly GO_SCRIPT_BASH_REPO_URL='https://github.com/mbland/go-script-bash.git'
 
 if [[ ! -e "$GO_SCRIPT_BASH_CORE" ]]; then
-  printf 'Cloning %s into %s...\n' "$GO_SCRIPT_BASH_REPO_URL" \
-    "${GO_SCRIPT_BASH_CORE%/*}"
+  printf "Cloning framework from '%s'...\n" "$GO_SCRIPT_BASH_REPO_URL"
   if ! git clone --depth 1 -c advice.detachedHead=false \
       -b "$GO_SCRIPT_BASH_VERSION" "$GO_SCRIPT_BASH_REPO_URL" \
-      "${GO_SCRIPT_BASH_CORE%/*}" &>/dev/null; then
-    printf 'Failed to clone %s; aborting.\n' "$GO_SCRIPT_BASH_REPO_URL" >&2
+      "${GO_SCRIPT_BASH_CORE%/*}"; then
+    printf "Failed to clone '%s'; aborting.\n" "$GO_SCRIPT_BASH_REPO_URL" >&2
     exit 1
   fi
+  printf "Clone of '%s' successful.\n\n" "$GO_SCRIPT_BASH_REPO_URL"
 fi
 
 . "$GO_SCRIPT_BASH_CORE" "${SCRIPTS_DIR##*/}"
