go-template: Minor formatting tweaks
This is in preparation for using `cp` instead of `wget` for `file://`
urls, since `wget` only supports HTTP, HTTPS, and FTP.

diff --git a/go-template b/go-template
--- a/go-template
+++ b/go-template
@@ -50,15 +50,17 @@ declare GO_SCRIPT_BASH_DOWNLOAD_URL="${GO_SCRIPT_BASH_DOWNLOAD_URL:-${GO_SCRIPT_
 download_go_script_bash_tarball() {
   # GitHub removes the leading 'v' from the archive's output directory.
   local unpacked_dir="go-script-bash-${GO_SCRIPT_BASH_VERSION#v}"
+  local unpacked_core="$unpacked_dir/go-core.bash"
   local core_dir_parent="${GO_SCRIPT_BASH_CORE_DIR%/*}"
+  local url="$GO_SCRIPT_BASH_DOWNLOAD_URL"
   local download_cmd=()
 
   if command -v curl >/dev/null; then
-    download_cmd=(curl -LfsS)
-  elif command -v wget >/dev/null; then
-    download_cmd=(wget -O -)
+    download_cmd=(curl -LfsS "$url")
   elif command -v fetch >/dev/null; then
-    download_cmd=(fetch -o -)
+    download_cmd=(fetch -o - "$url")
+  elif command -v wget >/dev/null; then
+    download_cmd=(wget -O - "$url")
   else
     printf "Failed to find cURL, wget, or fetch\n" >&2
     return 1
@@ -68,11 +70,10 @@ download_go_script_bash_tarball() {
     printf "Failed to find tar\n" >&2
     return 1
   fi
-  printf "Downloading framework from '%s'...\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL"
+  printf "Downloading framework from '%s'...\n" "$url"
 
-  if ! tar -xzf <("${download_cmd[@]}" "$GO_SCRIPT_BASH_DOWNLOAD_URL") ||
-    [[ ! -f "$unpacked_dir/go-core.bash" ]]; then
-    printf "Failed to download from '%s'.\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL" >&2
+  if ! tar -xzf <("${download_cmd[@]}") || [[ ! -f "$unpacked_core" ]]; then
+    printf "Failed to download from '%s'.\n" "$url" >&2
     return 1
   elif [[ ! -d "$core_dir_parent" ]] && ! mkdir -p "$core_dir_parent" ; then
     printf "Failed to create scripts dir '%s'\n" "$core_dir_parent" >&2
@@ -84,7 +85,7 @@ download_go_script_bash_tarball() {
     rm -rf "$unpacked_dir"
     return 1
   fi
-  printf "Download of '%s' successful.\n\n" "$GO_SCRIPT_BASH_DOWNLOAD_URL"
+  printf "Download of '%s' successful.\n\n" "$url"
 }
 
 git_clone_go_script_bash() {
