Support GNU tar check and increase template test coverage

diff --git a/go-template b/go-template
--- a/go-template
+++ b/go-template
@@ -60,7 +60,7 @@ if [[ ! -e "$GO_SCRIPT_BASH_CORE_DIR/go-core.bash" ]]; then
       printf "Failed to find cURL or tar\n"
       return 1
     fi
-    if ! command tar -h >/dev/null; then
+    if ! command tar --help >/dev/null; then
       printf "Failed to find cURL or tar\n"
       return 1
     fi
@@ -70,7 +70,7 @@ if [[ ! -e "$GO_SCRIPT_BASH_CORE_DIR/go-core.bash" ]]; then
       return 1
     fi
     if ! mkdir -p $GO_SCRIPTS_DIR ; then
-      printf "Failed to create scripts dir '%s'" $GO_SCRIPTS_DIR >&2
+      printf "Failed to create scripts dir '%s'\n" $GO_SCRIPTS_DIR >&2
       rm -rf go-script-bash-$_GO_SCRIPT_BASH_VERSION_NUMBER
       return 1
     fi
