get file: Recommend curl if any other tool fails
Turns out `wget` is part of BusyBox on Alpine Linux and has a completely
different error message. Also, seeing as I'm going to add FreeBSD `fetch`
support, probably makes sense to provide the `curl` recommendation for any tool
that fails that isn't curl.

diff --git a/libexec/get.d/file b/libexec/get.d/file
--- a/libexec/get.d/file
+++ b/libexec/get.d/file
@@ -96,9 +96,9 @@ _@go.fetch_file_impl() {
   if ! "${dl_cmd[@]}" "$url" 2>"$errfile"; then
     errmsg="$(< "$errfile")"
     printf '%s\n' "$errmsg" >&2
-    @go.printf 'Failed to download: %s' "$url" >&2
+    @go.printf 'Failed to download using %s: %s' "${dl_cmd[0]}" "$url" >&2
 
-    if [[ "${dl_cmd[0]}" == 'wget' && "$errmsg" =~ Unsupported\ scheme ]]; then
+    if [[ "${dl_cmd[0]}" != 'curl' ]]; then
       @go.printf 'Consider installing `curl` and trying again.\n' >&2
     fi
 
