lib/testing: Add assert_log{,_file}_equals tests

diff --git a/lib/testing/log b/lib/testing/log
--- a/lib/testing/log
+++ b/lib/testing/log
@@ -5,6 +5,10 @@
 # You must source `_GO_CORE_DIR/lib/testing/environment` before this file.
 
 . "${BASH_SOURCE[0]%/*}/stack-trace"
+. "$_GO_CORE_DIR/lib/bats/assertions"
+
+# Log timestamps are disabled by for testing by default.
+export _GO_LOG_TIMESTAMP_FORMAT=
 
 # Creates a `./go` script that imports the `log` module
 #
@@ -51,6 +55,24 @@ format_log_label() {
   printf '%s' "${__GO_LOG_LEVELS_FORMATTED[$__go_log_level_index]}"
 }
 
+# Validates that `output` matches the expected `@go.log` output
+#
+# Each line can be expressed one of two ways:
+# - As a pair of strings: first the log level label, then the log message
+# - As a single string without a log level label prefix
+#
+# Each log level label must exist within `_GO_LOG_LEVELS`, and can be either a
+# plaintext label or a label formatted with `format_log_label`. Any unknown
+# labels will be parsed as "a single string without a log label prefix".
+#
+# If you aren't looking for exact log output, consider using one of the standard
+# assertions from `_GO_CORE_DIR/lib/bats/assertions` instead.
+#
+# Note that this does NOT handle timestamps. If you wish to validate specific
+# timestamps, see `_GO_CORE_DIR/tests/log/timestamp.bats` for ideas.
+#
+# Arguments:
+#   ...:  Lines of expected log output
 assert_log_equals() {
   set "$BATS_ASSERTION_DISABLE_SHELL_OPTIONS"
   local __log_level_label
@@ -69,7 +91,7 @@ assert_log_equals() {
       fi
 
       if ! shift 2; then
-        echo "ERROR: Wrong number of arguments for log line $i." >&2
+        printf 'ERROR: Wrong number of arguments for log line %d.\n' "$i" >&2
         return_from_bats_assertion 1
         return
       fi
@@ -86,6 +108,24 @@ assert_log_equals() {
   fi
 }
 
+# Validates that a file matches the expected `@go.log` output
+#
+# Aside from the first file path argument, the remaining arguments and semantics
+# are exactly the same as `assert_log_equals`.
+#
+# In cases where `@go.log_add_output_file` is used to add a `TEST_LOG_FILE` to
+# all levels, and all test output comes from `@go.log`, this may be invoked
+# following `assert_log_equals` like so to ensure the log file output matches
+# standard output and standard error:
+#
+#   assert_log_file_equals "$TEST_LOG_FILE" "${lines[@]}"
+#
+# If you aren't looking for exact log output, consider using one of the standard
+# assertions from `_GO_CORE_DIR/lib/bats/assertions` instead.
+#
+# Arguments:
+#   log_file:  Path to the log file to validate
+#   ...:       Lines of expected log output
 assert_log_file_equals() {
   set "$BATS_ASSERTION_DISABLE_SHELL_OPTIONS"
   local log_file="$1"
@@ -130,6 +170,16 @@ set_log_command_stack_trace_items() {
 # None of the functions below this line are part of the public interface.
 # --------------------------------
 
+# Determines whether a log level label is a valid member of `_GO_LOG_LEVELS`.
+#
+# If so, pads the label and assigns it to `__log_level_label`.
+#
+# Arguments:
+#   level_label:  Log level label to examine
+#
+# Returns:
+#   zero if `level_label` exists in `_GO_LOG_LEVELS`, nonzero otherwise
+#   __log_level_label:  Assigned the padded version of `level_label` if valid
 __parse_log_level_label() {
   local level_label="$1"
   local try_level
