ass-test: Improve failing script error message
Introduces the `ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE` variable, which
achieves several aims:

- abstracts common `expect_assertion_*` output
- makes this output easier to test
- provides more documentation for would-be assertion authors at the top
  of the file

Also contains other small tweaks, including the
`TEST_ASSERTION_SHELL_OPTIONS` variable and a fix to the
`return_from_bats_assertion` function comment.

diff --git a/lib/bats/assertion-test-helpers b/lib/bats/assertion-test-helpers
--- a/lib/bats/assertion-test-helpers
+++ b/lib/bats/assertion-test-helpers
@@ -18,7 +18,27 @@ fi
 # This is the file written to by `printf_to_test_output_file`.
 export TEST_OUTPUT_FILE="$BATS_TEST_ROOTDIR/test-output.txt"
 
-ASSERTION_TEST_SCRIPT="$BATS_TEST_ROOTDIR/assertion-test.bats"
+# Path to the script generated by `expect_assertion_*` to test whether
+# `return_from_bats_assertion` was called or not.
+readonly ASSERTION_TEST_SCRIPT="$BATS_TEST_ROOTDIR/assertion-test.bats"
+
+# Format for the error message emitted when `ASSERTION_TEST_SCRIPT` fails.
+# Should be called as:
+#   printf "$ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE\n" "${assertion%% *}" >&2
+export ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE=
+
+# Avoid exiting with an error on EOF with `!`.
+! read -rd '' ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE <<END_OF_FAILURE_MESSAGE
+The very first line of '%s' must be
+
+  set "\$BATS_ASSERTION_DISABLE_SHELL_OPTIONS"
+
+and it must call 'return_from_bats_assertion' from every return path.
+
+For details, see the comments for 'return_from_bats_assertion' from:
+
+  $_GO_CORE_DIR/lib/bats/assertions
+END_OF_FAILURE_MESSAGE
 
 # Validates that an assertion succeeds for the provided inputs
 #
@@ -37,6 +57,7 @@ expect_assertion_success() {
   local test_script="$ASSERTION_TEST_SCRIPT"
   local __assertion_output
   local __assertion_status
+  local expected_script_output=()
 
   __run_command_then_run_assertion_in_subshell "$run_cmd" "$assertion"
 
@@ -53,16 +74,20 @@ expect_assertion_success() {
   # assertion will show the passing assertion's stack, per issue #48.
   __run_assertion_test_script \
     "  run $run_cmd" \
+    "  failing_assertion() { [ 0 -eq 1 ]; }" \
     "  $assertion" \
-    '  assert_equal_numbers() { [ "$1" -eq "$2" ]; }' \
-    '  assert_equal_numbers 0 1'
+    "  failing_assertion"
 
-  __check_expected_output "$output" \
-    '1..1' \
-    "not ok 1 $BATS_TEST_DESCRIPTION" \
-    "# (from function \`assert_equal_numbers' in file $test_script, line 6," \
-    "#  in test file $test_script, line 7)" \
-    "#   \`assert_equal_numbers 0 1' failed"
+  expected_script_output=('1..1'
+    "not ok 1 $BATS_TEST_DESCRIPTION"
+    "# (from function \`failing_assertion' in file $test_script, line 5,"
+    "#  in test file $test_script, line 7)"
+    "#   \`failing_assertion' failed")
+
+  if ! __check_expected_output "$output" "${expected_script_output[@]}"; then
+    printf "$ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE" "${assertion%% *}" >&2
+    return 1
+  fi
 }
 
 # Validates that an assertion fails for the provided inputs
@@ -84,6 +109,7 @@ expect_assertion_failure() {
   local __assertion_output
   local __assertion_status
   local with_status
+  local expected_script_output=()
 
   __run_command_then_run_assertion_in_subshell "$run_cmd" "$assertion"
 
@@ -98,18 +124,16 @@ expect_assertion_failure() {
   __check_expected_output "$__assertion_output" "$@"
   __run_assertion_test_script "  run $run_cmd" "  $assertion"
 
-  if [[ "$status" -eq '0' ]]; then
-    printf "In script: expected failure, but succeeded\nOutput:\n%s\n" \
-      "$output" >&2
+  expected_script_output=('1..1'
+    "not ok 1 $BATS_TEST_DESCRIPTION"
+    "# (in test file $ASSERTION_TEST_SCRIPT, line 5)"
+    "#   \`$assertion' failed${with_status}"
+    "${@/#/# }")
+
+  if ! __check_expected_output "$output" "${expected_script_output[@]}"; then
+    printf "$ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE" "${assertion%% *}" >&2
     return 1
   fi
-
-  __check_expected_output "$output" \
-    '1..1' \
-    "not ok 1 $BATS_TEST_DESCRIPTION" \
-    "# (in test file $ASSERTION_TEST_SCRIPT, line 5)" \
-    "#   \`$assertion' failed${with_status}" \
-    "${@/#/# }"
 }
 
 # Calls `printf` on its arguments and returns an error
