ass-test-help: Remove lib/bats/helpers dependency
This helps ensure that the assertion library or test environment imports
everything it needs rather than relying on this file.

diff --git a/lib/bats/assertion-test-helpers b/lib/bats/assertion-test-helpers
--- a/lib/bats/assertion-test-helpers
+++ b/lib/bats/assertion-test-helpers
@@ -30,14 +30,19 @@ if [[ -z "$ASSERTION_SOURCE" ]]; then
 fi
 
 . "$ASSERTION_SOURCE"
-. "${BASH_SOURCE%/*}/helpers"
+
+# Temp directory for assertion test artifacts.
+#
+# Defined the same as `BATS_TEST_ROOTDIR` from `lib/bats/helpers`, but not
+# dependent on it, so this file remains self-contained.
+export ASSERTION_TEST_ROOTDIR="${BATS_TEST_ROOTDIR:-$BATS_TMPDIR/test rootdir}"
 
 # This is the file written to by `printf_to_test_output_file`.
-export TEST_OUTPUT_FILE="$BATS_TEST_ROOTDIR/test-output.txt"
+export TEST_OUTPUT_FILE="$ASSERTION_TEST_ROOTDIR/test-output.txt"
 
 # Path to the script generated by `expect_assertion_*` to test whether
 # `restore_bats_shell_options` was called or not.
-readonly ASSERTION_TEST_SCRIPT="$BATS_TEST_ROOTDIR/assertion-test.bats"
+readonly ASSERTION_TEST_SCRIPT="$ASSERTION_TEST_ROOTDIR/assertion-test.bats"
 
 # Format for the error message emitted when `ASSERTION_TEST_SCRIPT` fails.
 # Should be called as:
@@ -202,8 +207,8 @@ export -f printf_with_error
 # Arguments:
 #   ...:  Arguments to `printf`
 printf_to_test_output_file() {
-  if [[ ! -d "$BATS_TEST_ROOTDIR" ]]; then
-    mkdir "$BATS_TEST_ROOTDIR"
+  if [[ ! -d "$ASSERTION_TEST_ROOTDIR" ]]; then
+    mkdir "$ASSERTION_TEST_ROOTDIR"
   fi
   printf "$@" >"$TEST_OUTPUT_FILE"
 }
@@ -270,12 +275,26 @@ __run_command_and_assertion_in_subshell() {
 # Arguments:
 #   ...: Body of the test case to execute
 __run_assertion_test_script() {
-  create_bats_test_script "${ASSERTION_TEST_SCRIPT#$BATS_TEST_ROOTDIR/}" \
-    '#! /usr/bin/env bats' \
-    "load '$ASSERTION_SOURCE'" \
-    "@test \"$BATS_TEST_DESCRIPTION\" {" \
-    "$@" \
-    '}'
+  local script_dir="${ASSERTION_TEST_SCRIPT%/*}"
+  local script_impl=('#! /usr/bin/env bats'
+    "load '$ASSERTION_SOURCE'"
+    "@test \"$BATS_TEST_DESCRIPTION\" {"
+    "$@"
+    '}')
+
+  if [[ ! -d "$script_dir" ]] && ! mkdir -p "$script_dir"; then
+    printf 'Failed to create parent directory for assertion test script: %s\n' \
+      "$ASSERTION_TEST_SCRIPT" >&2
+    return '1'
+  elif ! printf '%s\n' "${script_impl[@]}" >"$ASSERTION_TEST_SCRIPT"; then
+    printf 'Failed to create assertion test script: %s\n' \
+      "$ASSERTION_TEST_SCRIPT" >&2
+    return '1'
+  elif ! chmod 755 "$ASSERTION_TEST_SCRIPT"; then
+    printf 'Failed to set permissions for assertion test script: %s\n' \
+      "$ASSERTION_TEST_SCRIPT" >&2
+    return '1'
+  fi
   run "$ASSERTION_TEST_SCRIPT"
 }
 
