assertions: Introduce bats_assertion_return_trap
It's a lot more straightforward to understand and use than
`return_from_bats_assertion`.

diff --git a/lib/bats/assertions b/lib/bats/assertions
--- a/lib/bats/assertions
+++ b/lib/bats/assertions
@@ -24,16 +24,13 @@
 #     fail "output should not match: '$pattern'"
 #   fi
 #
-# Alternatively, write your own assertion functions starting with:
+# Alternatively, write your own assertion functions that call the following
+# before returning:
 #
 #   set +o functrace
+#   trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
 #
-# and then make sure every return path calls:
-#
-#   return_from_bats_assertion "$return_status" "$BASH_SOURCE"
-#
-# You may wish to wrap `return_from_bats_assertion` in a local helper function
-# to avoid having to specify `$BASH_SOURCE` everywhere.
+# See the comment for `bats_assertion_return_trap` for more details.
 #
 # The assertions borrow inspiration from rbenv/test/test_helper.bash.
 
@@ -46,13 +43,14 @@
 #   $1:  (optional) Reason to include in the failure output
 fail() {
   set +o functrace
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
   local reason="$1"
 
   if [[ -n "$reason" ]]; then
     printf 'failed for the following reason:\n  %s\n' "$reason" >&2
   fi
   printf 'STATUS: %s\nOUTPUT:\n%s\n' "$status" "$output" >&2
-  __return_from_bats_assertion 1
+  return 1
 }
 
 # Compares two values for equality
@@ -63,6 +61,7 @@ fail() {
 #   $3: A label explaining the value being evaluated
 assert_equal() {
   set +o functrace
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
   local expected="$1"
   local actual="$2"
   local label="$3"
@@ -70,9 +69,7 @@ assert_equal() {
   if [[ "$expected" != "$actual" ]]; then
     printf '%s not equal to expected value:\n  %s\n  %s\n' \
       "$label" "expected: '$expected'" "actual:   '$actual'" >&2
-    __return_from_bats_assertion 1
-  else
-    __return_from_bats_assertion
+    return 1
   fi
 }
 
@@ -84,6 +81,7 @@ assert_equal() {
 #   $3: A label explaining the value being matched
 assert_matches() {
   set +o functrace
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
   local pattern="$1"
   local value="$2"
   local label="$3"
@@ -91,9 +89,7 @@ assert_matches() {
   if [[ ! "$value" =~ $pattern ]]; then
     printf '%s does not match expected pattern:\n  %s\n  %s\n' \
       "$label" "pattern: '$pattern'" "value:   '$value'" >&2
-    __return_from_bats_assertion 1
-  else
-    __return_from_bats_assertion
+    return 1
   fi
 }
 
@@ -121,6 +117,7 @@ assert_output_matches() {
 #   $1: The expected value for $status
 assert_status() {
   set +o functrace
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
   assert_equal "$1" "$status" "exit status"
 }
 
@@ -130,13 +127,13 @@ assert_status() {
 #   $1: The regular expression to match against $output
 assert_success() {
   set +o functrace
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
+
   if [[ "$status" -ne '0' ]]; then
     printf 'expected success, but command failed\n' >&2
     fail
   elif [[ "$#" -ne 0 ]]; then
     assert_output "$@"
-  else
-    __return_from_bats_assertion
   fi
 }
 
@@ -146,13 +143,13 @@ assert_success() {
 #   $1: The regular expression to match against $output
 assert_failure() {
   set +o functrace
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
+
   if [[ "$status" -eq '0' ]]; then
     printf 'expected failure, but command succeeded\n' >&2
     fail
   elif [[ "$#" -ne 0 ]]; then
     assert_output "$@"
-  else
-    __return_from_bats_assertion
   fi
 }
 
@@ -178,15 +175,25 @@ assert_line_matches() {
 
 # Scrubs the Bats stacks of functions from the assertion source file
 #
-# You must ensure that `set +o functrace` is in effect prior to calling this
-# function. If you write an assertion function that uses an assertion from this
-# file, or which uses any other assertion that evantually calls this function,
-# you will need to call `set +o functrace` again following those assertions.
-#
 # This helps ensure that Bats failure messages only contain the location at
 # which an assertion was called, rather than containing stack trace information
 # about the assertion implementation itself.
 #
+# You must ensure that `set +o functrace` is in effect prior to calling this
+# function. Usually you'll do this by making these the first two lines of your
+# assertion function, or by adding them just before returning an error value (if
+# you accumulate multiple assertion errors in one function, since each assertion
+# may reset `set -e functrace`):
+#
+#   set +o functrace
+#   trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
+#
+# Or, if you have a shared implementation function, call `set +o functrace` at
+# the beginning of each public-facing function, and set the trap in the
+# implementation function, as with __assert_output and __assert_line.
+#
+# Background
+# ----------
 # Bats sets 'functrace' to make sure failing commands are pinpointed. This is
 # almost always the desired behavior, except that we don't actually want a stack
 # trace showing assertion implementation details. When it does, it produces a
@@ -201,21 +208,14 @@ assert_line_matches() {
 #
 # Arguments:
 #   $1:  The $BASH_SOURCE value from the assertion source file
-#   $2:  Return value of the calling assertion; defaults to 0
-return_from_bats_assertion() {
-  local assertion_source_file="$1"
-  local result="${2:-0}"
-
-  if [[ "${BATS_CURRENT_STACK_TRACE[0]}" =~ $assertion_source_file ]]; then
+bats_assertion_return_trap() {
+  if [[ "${BATS_CURRENT_STACK_TRACE[0]}" =~ $1 ]]; then
     unset 'BATS_CURRENT_STACK_TRACE[0]'
   fi
-
-  if [[ "${BATS_PREVIOUS_STACK_TRACE[0]}" =~ $assertion_source_file ]]; then
+  if [[ "${BATS_PREVIOUS_STACK_TRACE[0]}" =~ $1 ]]; then
     unset 'BATS_PREVIOUS_STACK_TRACE[0]'
   fi
-
   set -o functrace
-  return "$result"
 }
 
 # --------------------------------
@@ -230,12 +230,13 @@ return_from_bats_assertion() {
 #   $1: The assertion to execute
 #   $2: The assertion argument signifying the expected outcome for $output
 __assert_output() {
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
   local assertion="$1"
   local constraint="$2"
 
   if [[ "$#" -ne 2 ]]; then
     echo "ERROR: ${FUNCNAME[1]} takes exactly one argument" >&2
-    __return_from_bats_assertion 1
+    return 1
   else
     "$assertion" "$constraint" "$output" 'output'
   fi
@@ -248,6 +249,7 @@ __assert_output() {
 #   $2: The index into $line identifying the line to evaluate
 #   $3: The assertion argument signifying the expected outcome for ${line[$2]}
 __assert_line() {
+  trap "bats_assertion_return_trap '$BASH_SOURCE'" RETURN
   local assertion="$1"
   local lineno="$2"
   local constraint="$3"
@@ -259,18 +261,6 @@ __assert_line() {
 
   if ! "$assertion" "$constraint" "${lines[$lineno]}" "line $lineno"; then
     printf 'OUTPUT:\n%s\n' "$output" >&2
-    __return_from_bats_assertion 1
-  else
-    __return_from_bats_assertion
+    return 1
   fi
-}
-
-# Scrubs the Bats stacks of references to functions from this file
-#
-# See the comment for return_from_bats_assertion for details.
-#
-# Arguments:
-#   $1:  Return value of the calling assertion; defaults to 0
-__return_from_bats_assertion() {
-  return_from_bats_assertion "$BASH_SOURCE" "$1"
 }
