commands: Refactor find to use mergesort
Ended up being about ten more lines of code and only very slightly faster, but I
like how everything is better separated now. Specifically, the
`__go_command_names` array is assigned in one statement after all scripts have
been discovered, and `__go_longest_name_len` is determined after that.

diff --git a/lib/commands b/lib/commands
--- a/lib/commands
+++ b/lib/commands
@@ -1,70 +1,80 @@
 #! /bin/bash
 
-# Note that _@go.find_commands uses this insertion sort rather than `sort |
+# Note that _@go.merge_scripts_into_list uses this mergesort rather than `sort |
 # uniq` not just because it's is more portable (to Windows), but because it's
 # actually faster for the amount of data involved, since it avoids the overhead
 # of launching the `sort | uniq` pipeline. Since the user's expected to invoke
 # this frequently via the 'help' command and tab completion, scraping out this
 # tiny bit of performance potentially matters. (And it keeps the tests fast.)
-_@go.insert_name_and_script() {
-  local cmd_name="$1"
-  local cmd_script="$2"
+_@go.merge_scripts_into_list() {
+  local scripts=("$@")
   local i=0
-  local current_name
-  local current_script
+  local j=0
+  local lhs_script
+  local lhs_name
+  local rhs_script
+  local rhs_name
+  local result=()
 
-  for ((i=${#__go_command_names[@]}; i != 0; --i)); do
-    current_name="${__go_command_names[$((i-1))]}"
-    current_script="${__go_command_scripts[$((i-1))]}"
+  while ((i != ${#__go_command_scripts[@]} && j != ${#scripts[@]})); do
+    lhs_script="${__go_command_scripts[$i]}"
+    rhs_script="${scripts[$j]}"
+    lhs_name="${lhs_script##*/}"
+    rhs_name="${rhs_script##*/}"
 
-    if [[ "$cmd_name" = "$current_name" ]]; then
-      printf "ERROR: duplicate command $cmd_name:\n\n  %s\n  %s\n" \
-        "$current_script" "$cmd_script" >&2
+    if [[ "$lhs_name" = "$rhs_name" ]]; then
+      printf "ERROR: duplicate command $lhs_name:\n\n  %s\n  %s\n" \
+        "$lhs_script" "$rhs_script" >&2
       return 1
-    elif [[ "$cmd_name" < "$current_name" ]]; then
-      __go_command_names[$i]="$current_name"
-      __go_command_scripts[$i]="$current_script"
+    elif [[ "$lhs_name" < "$rhs_name" ]]; then
+      result+=("$lhs_script")
+      ((++i))
     else
-      break
+      result+=("$rhs_script")
+      ((++j))
     fi
   done
 
-  __go_command_names[$i]="$cmd_name"
-  __go_command_scripts[$i]="$cmd_script"
+  __go_command_scripts=(
+    "${result[@]}" "${__go_command_scripts[@]:$i}" "${scripts[@]:$j}")
 }
 
 _@go.find_commands() {
-  local scripts_dir
-  local cmd_script
-  local cmd
-
-  __go_longest_name_len=0
-  __go_command_names=()
   __go_command_scripts=()
+  __go_command_names=()
+  __go_longest_name_len=0
 
-  shopt -s nullglob
+  local scripts_dir
+  local script
+  local scripts
 
   for scripts_dir in "$@"; do
-    for cmd_script in "$scripts_dir"/*; do
-      if [[ ! (-f "$cmd_script" && -x "$cmd_script") ]]; then
-        continue
-      fi
+    scripts=()
 
-      cmd="${cmd_script##*/}"
-      cmd_script="${cmd_script#$_GO_ROOTDIR/}"
-      if ! _@go.insert_name_and_script "$cmd" "$cmd_script"; then
-        return 1
-      fi
-
-      if [[ "${#cmd}" -gt "$__go_longest_name_len" ]]; then
-        __go_longest_name_len="${#cmd}"
+    shopt -s nullglob
+    for script in $scripts_dir/*; do
+      if [[ -f "$script" && -x "$script" ]]; then
+        scripts+=("$script")
       fi
     done
+    shopt -u nullglob
+
+    if ! _@go.merge_scripts_into_list "${scripts[@]#$_GO_ROOTDIR/}"; then
+      return 1
+    fi
   done
 
-  shopt -u nullglob
-
-  if [[ "${#__go_command_names[@]}" -eq '0' ]]; then
+  if [[ "${#__go_command_scripts[@]}" -eq '0' ]]; then
     return 1
   fi
+
+  __go_command_names=("${__go_command_scripts[@]##*/}")
+
+  local cmd_name
+
+  for cmd_name in "${__go_command_names[@]}"; do
+    if [[ "$__go_longest_name_len" -lt "${#cmd_name}" ]]; then
+      __go_longest_name_len="${#cmd_name}"
+    fi
+  done
 }
