prompt: Add prompt_for_yes_or_no

diff --git a/lib/prompt b/lib/prompt
--- a/lib/prompt
+++ b/lib/prompt
@@ -9,6 +9,9 @@
 #   @go.prompt_for_input
 #     Prompts the user for a line of input
 #
+#   @go.prompt_for_yes_or_no
+#     Prompts the user for a yes or no response
+#
 #   @go.select_option
 #     Prompts the user to select one item from a list of options
 
@@ -56,6 +59,53 @@
     @go.printf '%s\n' "$4" >&2
     return 1
   fi
+}
+
+# Prompts the user for a yes or no response
+#
+# Arguments:
+#   prompt   Text prompt for user input
+#   default  (Optional) Default response; must be 'yes' or 'no'
+#
+# Returns:
+#   Zero on 'y' or 'yes' (case- and space- insensitive), nonzero otherwise
+@go.prompt_for_yes_or_no() {
+  local prompt="$1"
+  local default="$2"
+  local response
+
+  case "$default" in
+  yes)
+    @go.printf '%s [Y/n] ' "$prompt" >&2
+    ;;
+  no)
+    @go.printf '%s [y/N] ' "$prompt" >&2
+    ;;
+  '')
+    @go.printf '%s [y/n] ' "$prompt" >&2
+    ;;
+  *)
+    @go.printf 'Invalid `default` parameter "%s" for %s at:\n' \
+      "$default" "$FUNCNAME" >&2
+    @go.print_stack_trace '1' >&2
+    exit 1
+    ;;
+  esac
+
+  while true; do
+    @go.read_prompt_response 'response' "$default"
+
+    if [[ "$response" =~ ^[Yy]([Ee][Ss])?$ ]]; then
+      return 0
+    elif [[ "$response" =~ ^[Nn]([Oo])?$ ]]; then
+      return 1
+    else
+      if [[ -n "$response" ]]; then
+        @go.printf '\n"%s" is an invalid response.\n' "$response" >&2
+      fi
+      @go.printf '\nPlease answer Y(es) or N(o): ' >&2
+    fi
+  done
 }
 
 # Prompts the user to select one item from a list of options.
