commands: Expand tab completion capability

diff --git a/libexec/commands b/libexec/commands
--- a/libexec/commands
+++ b/libexec/commands
@@ -68,8 +68,11 @@ _@go.commands_parse_argv() {
 
   if [[ "$#" -eq 0 ]]; then
     __go_commands_search_paths=("${_GO_SEARCH_PATHS[@]}")
-  elif [[ "$#" -eq '1' && ( "$1" =~ : || -d "$1" ) ]]; then
-    if ! _@go.commands_parse_search_paths "$1"; then
+  elif [[ "$1" =~ : || -d "$1" ]]; then
+    if [[ "$#" -ne 1 ]]; then
+      @go.printf 'Cannot specify any arguments after search paths.\n' >&2
+      return 1
+    elif ! _@go.commands_parse_search_paths "$1"; then
       return 1
     fi
   else
@@ -91,10 +94,29 @@ _@go.commands_tab_completions() {
   shift
 
   if [[ "$word_index" -eq '0' ]]; then
-    compgen -W '--paths --summaries' -- "$1"
-  else
+    local flag_result=0
+    if ! compgen -W '--paths --summaries' -- "$1"; then
+      ((++flag_result))
+    fi
+    if [[ "${1:0:1}" == '-' || "$#" -gt 1 ]]; then
+      return $flag_result
+    fi
+  fi
+
+  if [[ "${1:0:1}" == '-' ]]; then
+    shift
+    ((--word_index))
+  elif [[ "$1" =~ : || -d "$1" ]]; then
     return 1
   fi
+
+  local args=("$@")
+  local last_arg_index="$((${#args[@]} - 1))"
+  if [[ "$word_index" -lt "$last_arg_index" ]]; then
+    return 1
+  fi
+  compgen -W "$(_@go.commands "${args[@]:0:$word_index}")" -- \
+    "${args[$word_index]}"
 }
 
 _@go.commands() {
