use: Improve module import error message
It could be that the module has syntax errors, or that it failed to
define or import all its necessary functions and variables, or that it
deliberately raised an error based on an error condition. It's better to
state plainly that the import failed, and permit the user to ascertain
the cause from the module's output, rather than making it sound like the
module script is broken.

diff --git a/lib/internal/use b/lib/internal/use
--- a/lib/internal/use
+++ b/lib/internal/use
@@ -90,14 +90,14 @@ for __go_module_name in "$@"; do
       __go_module_file="$_GO_SCRIPTS_DIR/lib/$__go_module_name"
 
       if [[ ! -f "$__go_module_file" ]]; then
-        @go.printf "ERROR: Unknown module: $__go_module_name" >&2
+        @go.printf "ERROR: Unknown module: $__go_module_name\n" >&2
         exit 1
       fi
     fi
   fi
 
   if ! . "$__go_module_file"; then
-    @go.printf "ERROR: Module contains errors: $__go_module_file" >&2
+    @go.printf "ERROR: Module import failed for: $__go_module_file\n" >&2
     exit 1
   fi
 done
