use: Use _@go.use_modules wrapper
This is part of the refactoring of `_GO_USE_MODULES` to provide correct
`@go` command script scope for plugin modules.

This also eliminates the need for `_@go.set_use_caller`.

diff --git a/lib/internal/use b/lib/internal/use
--- a/lib/internal/use
+++ b/lib/internal/use
@@ -73,19 +73,6 @@
 #   for modules imported within a Bash command script or function:
 #   @go modules --imported
 
-declare __go_module_name
-declare __go_module_file
-declare __go_loaded_module
-declare __go_loaded_file
-declare __go_module_index
-declare __go_use_caller
-declare __go_use_prev_caller
-
-# Wrapper function necessary due to BASH_SOURCE and FUNCNAME bug in Bash <4.3.
-_@go.set_use_caller() {
-  __go_use_caller="${BASH_SOURCE[2]}:${BASH_LINENO[1]} ${FUNCNAME[2]}"
-}
-
 _@go.find_plugin_module() {
   [[ -f "$1/$__go_module_file" ]] && __go_module_file="$1/$__go_module_file"
 }
@@ -111,75 +98,77 @@ _@go.find_module() {
   fi
 }
 
-for __go_module_name in "$@"; do
-  # Since every import is in the same scope, setting the caller each time is
-  # necessary in case any imported modules import other modules.
-  _@go.set_use_caller
-  __go_module_file="$_GO_CORE_DIR/lib/$__go_module_name"
+_@go.use_modules() {
+  local __go_module_name
+  local __go_module_file
+  local loaded_module
+  local loaded_file
+  local module_index
+  local __go_use_caller="${BASH_SOURCE[2]}:${BASH_LINENO[1]} ${FUNCNAME[2]}"
+  local prev_caller
 
-  if [[ -n "$_GO_INJECT_MODULE_PATH" ]]; then
-    __go_module_file="$_GO_INJECT_MODULE_PATH/$__go_module_name"
-    if [[ ! -f "$__go_module_file" ]]; then
-      __go_module_file="$_GO_CORE_DIR/lib/$__go_module_name"
-    fi
-  fi
+  for __go_module_name in "$@"; do
+    __go_module_file="$_GO_CORE_DIR/lib/$__go_module_name"
 
-  if [[ ! -f "$__go_module_file" ]] && ! _@go.find_module; then
-    @go.printf 'ERROR: Module %s not found at:\n' "$__go_module_name" >&2
-    @go.print_stack_trace 1 >&2
-    exit 1
-  fi
-
-  # If we found the module in our project, but we're installed as a plugin,
-  # change the loaded module name to reflect that.
-  #
-  # Using `##` to trim the string instead of `#` flattens the module name
-  # namespace. We could use `#` to keep it hierarchical, but since the Bash
-  # namespace itself is flat, this might lead to hard-to-debug collisions if
-  # functions and variables get redefined. Keeping a flat module name namespace
-  # allows us to detect such potential collisions and issue a warning below.
-  if [[ "$__go_module_file" =~ ^$_GO_PLUGINS_DIR ]]; then
-    __go_module_name="${__go_module_file##*/plugins/}"
-    __go_module_name="${__go_module_name/\/bin\///}"
-    __go_module_name="${__go_module_name/\/lib\///}"
-  fi
-
-  __go_module_index=0
-  for __go_loaded_module in "${_GO_IMPORTED_MODULES[@]}"; do
-    if [[ "$__go_module_name" == "$__go_loaded_module" ]]; then
-      __go_loaded_file="${_GO_IMPORTED_MODULE_FILES[$__go_module_index]}"
-      __go_use_prev_caller="${_GO_IMPORTED_MODULE_CALLERS[$__go_module_index]}"
-
-      # This may happen if a plugin appears more than once in a project tree.
-      if [[ "$__go_module_file" != "$__go_loaded_file" ]]; then
-        @go.printf '%s\n' "WARNING: Module: $__go_module_name" \
-          "imported at: $__go_use_caller" \
-          "from file: $__go_module_file" \
-          "previously imported at: $__go_use_prev_caller" \
-          "from file: $__go_loaded_file" >&2
+    if [[ -n "$_GO_INJECT_MODULE_PATH" ]]; then
+      __go_module_file="$_GO_INJECT_MODULE_PATH/$__go_module_name"
+      if [[ ! -f "$__go_module_file" ]]; then
+        __go_module_file="$_GO_CORE_DIR/lib/$__go_module_name"
       fi
-      continue 2
     fi
-    ((++__go_module_index))
+
+    if [[ ! -f "$__go_module_file" ]] && ! _@go.find_module; then
+      @go.printf 'ERROR: Module %s not found at:\n' "$__go_module_name" >&2
+      @go.print_stack_trace 1 >&2
+      exit 1
+    fi
+
+    # If we found the module in our project, but we're installed as a plugin,
+    # change the loaded module name to reflect that.
+    #
+    # Using `##` to trim the string instead of `#` flattens the module name
+    # namespace. We could use `#` to keep it hierarchical, but since the Bash
+    # namespace itself is flat, this might lead to hard-to-debug collisions if
+    # functions and variables get redefined. Keeping a flat module name
+    # namespace allows us to detect such potential collisions and issue a
+    # warning below.
+    if [[ "$__go_module_file" =~ ^$_GO_PLUGINS_DIR ]]; then
+      __go_module_name="${__go_module_file##*/plugins/}"
+      __go_module_name="${__go_module_name/\/bin\///}"
+      __go_module_name="${__go_module_name/\/lib\///}"
+    fi
+
+    module_index=0
+    for loaded_module in "${_GO_IMPORTED_MODULES[@]}"; do
+      if [[ "$__go_module_name" == "$loaded_module" ]]; then
+        loaded_file="${_GO_IMPORTED_MODULE_FILES[$module_index]}"
+        prev_caller="${_GO_IMPORTED_MODULE_CALLERS[$module_index]}"
+
+        # This may happen if a plugin appears more than once in a project tree.
+        if [[ "$__go_module_file" != "$loaded_file" ]]; then
+          @go.printf '%s\n' "WARNING: Module: $__go_module_name" \
+            "imported at: $__go_use_caller" \
+            "from file: $__go_module_file" \
+            "previously imported at: $prev_caller" \
+            "from file: $loaded_file" >&2
+        fi
+        continue 2
+      fi
+      ((++module_index))
+    done
+
+    # Prevent self- and circular importing by registering info before sourcing.
+    _GO_IMPORTED_MODULES+=("$__go_module_name")
+    _GO_IMPORTED_MODULE_FILES+=("$__go_module_file")
+    _GO_IMPORTED_MODULE_CALLERS+=("$__go_use_caller")
+
+    if ! . "$__go_module_file"; then
+      @go.printf 'ERROR: Failed to import %s module from %s at:\n' \
+        "$__go_module_name" "$__go_module_file" >&2
+      @go.print_stack_trace 1 >&2
+      exit 1
+    fi
   done
+}
 
-  # Prevent self- and circular importing by registering info before sourcing.
-  _GO_IMPORTED_MODULES+=("$__go_module_name")
-  _GO_IMPORTED_MODULE_FILES+=("$__go_module_file")
-  _GO_IMPORTED_MODULE_CALLERS+=("$__go_use_caller")
-
-  if ! . "$__go_module_file"; then
-    @go.printf 'ERROR: Failed to import %s module from %s at:\n' \
-      "$__go_module_name" "$__go_module_file" >&2
-    @go.print_stack_trace 1 >&2
-    exit 1
-  fi
-done
-
-unset __go_use_prev_caller
-unset __go_use_caller
-unset __go_module_index
-unset __go_loaded_file
-unset __go_loaded_module
-unset __go_module_file
-unset __go_module_name
+_@go.use_modules "$@"
