use: Nest module file path tests
It's slightly wasteful to keep issuing `-f "$__go_module_file"` checks
after finding a valid file path.

diff --git a/lib/internal/use b/lib/internal/use
--- a/lib/internal/use
+++ b/lib/internal/use
@@ -85,13 +85,15 @@ for __go_module_name in "$@"; do
   if [[ ! -f "$__go_module_file" ]]; then
     # Convert <plugin>/<module> to plugins/<plugin>/lib/<module>
     __go_module_file="$_GO_SCRIPTS_DIR/plugins/${__go_module_name/\///lib/}"
-  fi
-  if [[ ! -f "$__go_module_file" ]]; then
-    __go_module_file="$_GO_SCRIPTS_DIR/lib/$__go_module_name"
-  fi
-  if [[ ! -f "$__go_module_file" ]]; then
-    @go.printf "ERROR: Unknown module: $__go_module_name" >&2
-    exit 1
+
+    if [[ ! -f "$__go_module_file" ]]; then
+      __go_module_file="$_GO_SCRIPTS_DIR/lib/$__go_module_name"
+
+      if [[ ! -f "$__go_module_file" ]]; then
+        @go.printf "ERROR: Unknown module: $__go_module_name" >&2
+        exit 1
+      fi
+    fi
   fi
 
   if ! . "$__go_module_file"; then
